# Generated by Django 6.1.1 on 2026-09-15 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('licenciatura', models.CharField(blank=True, max_length=150, null=True)),
                ('universidad', models.CharField(blank=True, max_length=150, null=True)),
                ('promedio', models.FloatField(blank=True, null=True)),
                ('correo', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('ciclo', models.CharField(blank=True, max_length=10, null=True)),
                ('estado', models.CharField(default='Registrado', max_length=30)),
                ('evaluacion_curricular', models.FloatField(blank=True, null=True)),
                ('evaluacion_entrevista', models.FloatField(blank=True, null=True)),
                ('evaluacion_conocimientos', models.FloatField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=1000, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(blank=True, db_column='alumno_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumnos.alumno')),
            ],
            options={
                'db_table': 'aspirante',
            },
        ),
    ]
