# Generated by Django 6.1.1 on 2026-09-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('anio', models.IntegerField()),
                ('resumen', models.CharField(blank=True, max_length=500, null=True)),
                ('hora_inicio', models.CharField(blank=True, max_length=10, null=True)),
                ('hora_fin', models.CharField(blank=True, max_length=10, null=True)),
                ('lugar', models.CharField(blank=True, default='Puerto Vallarta, Jalisco', max_length=150, null=True)),
                ('sede', models.CharField(blank=True, max_length=250, null=True)),
                ('asistentes', models.CharField(blank=True, max_length=1000, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'acta',
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='ComiteMiembro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'comite_miembro',
            },
        ),
        migrations.CreateModel(
            name='ComiteTutorial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ciclo', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'comite_tutorial',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('Director', 'Director'), ('Codirector', 'Codirector')], max_length=12)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'direccion',
            },
        ),
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lector',
            },
        ),
        migrations.CreateModel(
            name='Sinodal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(blank=True, choices=[('Presidente', 'Presidente'), ('Secretario', 'Secretario'), ('Vocal', 'Vocal')], max_length=15, null=True)),
                ('fecha_examen', models.DateField(blank=True, null=True)),
                ('hora_examen', models.CharField(blank=True, max_length=10, null=True)),
                ('lugar_examen', models.CharField(blank=True, max_length=200, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sinodal',
            },
        ),
    ]
