# Generated by Django 6.1.1 on 2026-09-15 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actas', '0001_initial'),
        ('alumnos', '0001_initial'),
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comitemiembro',
            name='profesor',
            field=models.ForeignKey(db_column='profesor_id', on_delete=django.db.models.deletion.CASCADE, to='profesores.profesor'),
        ),
        migrations.AddField(
            model_name='comitetutorial',
            name='acta',
            field=models.ForeignKey(blank=True, db_column='acta_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='actas.acta'),
        ),
        migrations.AddField(
            model_name='comitetutorial',
            name='alumno',
            field=models.ForeignKey(db_column='alumno_id', on_delete=django.db.models.deletion.CASCADE, related_name='comites_tutoriales', to='alumnos.alumno'),
        ),
        migrations.AddField(
            model_name='comitemiembro',
            name='comite',
            field=models.ForeignKey(db_column='comite_id', on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='actas.comitetutorial'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='acta',
            field=models.ForeignKey(blank=True, db_column='acta_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='actas.acta'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='alumno',
            field=models.ForeignKey(db_column='alumno_id', on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='alumnos.alumno'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='profesor',
            field=models.ForeignKey(db_column='profesor_id', on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='profesores.profesor'),
        ),
        migrations.AddField(
            model_name='lector',
            name='acta',
            field=models.ForeignKey(blank=True, db_column='acta_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='actas.acta'),
        ),
        migrations.AddField(
            model_name='lector',
            name='alumno',
            field=models.ForeignKey(db_column='alumno_id', on_delete=django.db.models.deletion.CASCADE, related_name='lectores', to='alumnos.alumno'),
        ),
        migrations.AddField(
            model_name='lector',
            name='profesor',
            field=models.ForeignKey(db_column='profesor_id', on_delete=django.db.models.deletion.CASCADE, to='profesores.profesor'),
        ),
        migrations.AddField(
            model_name='sinodal',
            name='acta',
            field=models.ForeignKey(blank=True, db_column='acta_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='actas.acta'),
        ),
        migrations.AddField(
            model_name='sinodal',
            name='alumno',
            field=models.ForeignKey(db_column='alumno_id', on_delete=django.db.models.deletion.CASCADE, related_name='sinodales', to='alumnos.alumno'),
        ),
        migrations.AddField(
            model_name='sinodal',
            name='profesor',
            field=models.ForeignKey(db_column='profesor_id', on_delete=django.db.models.deletion.CASCADE, to='profesores.profesor'),
        ),
    ]
