# Generated by Django 6.1.1 on 2026-09-16 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0002_initial'),
        ('alumnos', '0001_initial'),
        ('documentos', '0002_plantillabase_tipodocumentopersonalizado'),
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoActa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orden', models.IntegerField()),
                ('tipo', models.CharField(choices=[('direccion', 'Dirección'), ('comite_tutorial', 'Comité Tutorial'), ('personalizado', 'Personalizado'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('titulo', models.CharField(max_length=300)),
                ('resolutivo', models.CharField(blank=True, max_length=2000, null=True)),
                ('rol', models.CharField(blank=True, max_length=12, null=True)),
                ('ciclo', models.CharField(blank=True, max_length=10, null=True)),
                ('datos_json', models.CharField(blank=True, max_length=4000, null=True)),
                ('acta', models.ForeignKey(db_column='acta_id', on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='actas.acta')),
                ('alumno', models.ForeignKey(blank=True, db_column='alumno_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumnos.alumno')),
                ('comite_tutorial', models.ForeignKey(blank=True, db_column='comite_tutorial_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='actas.comitetutorial')),
                ('direccion', models.ForeignKey(blank=True, db_column='direccion_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='actas.direccion')),
                ('profesor', models.ForeignKey(blank=True, db_column='profesor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='profesores.profesor')),
                ('tipo_documento', models.ForeignKey(blank=True, db_column='tipo_documento_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentos.tipodocumentopersonalizado')),
            ],
            options={
                'db_table': 'punto_acta',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PuntoActaMiembro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profesor', models.ForeignKey(db_column='profesor_id', on_delete=django.db.models.deletion.CASCADE, to='profesores.profesor')),
                ('punto', models.ForeignKey(db_column='punto_id', on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='actas.puntoacta')),
            ],
            options={
                'db_table': 'punto_acta_miembro',
            },
        ),
    ]
