# Generated by Django 6.1.1 on 2026-09-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('clave', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('valor', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'configuracion',
            },
        ),
        migrations.CreateModel(
            name='HistorialCambio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(blank=True, max_length=80, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('entidad', models.CharField(max_length=50)),
                ('entidad_id', models.IntegerField()),
                ('accion', models.CharField(choices=[('crear', 'crear'), ('modificar', 'modificar'), ('eliminar', 'eliminar')], max_length=20)),
                ('campo', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_anterior', models.CharField(blank=True, max_length=500, null=True)),
                ('valor_nuevo', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'historial_cambio',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Lies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'lies',
            },
        ),
        migrations.CreateModel(
            name='StatusAlumno',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('categoria', models.CharField(max_length=20)),
                ('confirmado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'status_alumno',
            },
        ),
    ]
