# Generated by Django 6.1.1 on 2026-09-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FolioSecuencia',
            fields=[
                ('tipo_documento', models.CharField(max_length=60)),
                ('anio', models.IntegerField()),
                ('ultimo_folio', models.IntegerField(default=0)),
                ('pk', models.CompositePrimaryKey('tipo_documento', 'anio', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'folio_secuencia',
            },
        ),
    ]
