# Generated by Django 6.1.1 on 2026-09-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaBase',
            fields=[
                ('categoria', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('archivo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'plantilla_base',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumentoPersonalizado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=60, unique=True)),
                ('etiqueta', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('categoria', models.CharField(max_length=20)),
                ('cuerpo_texto', models.TextField(blank=True, null=True)),
                ('plantilla_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('confirmado', 'Confirmado')], default='borrador', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tipo_documento_personalizado',
                'ordering': ['etiqueta'],
            },
        ),
    ]
