# Generated by Django 6.1.1 on 2026-09-15 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('ciclo_ingreso', models.CharField(blank=True, max_length=10, null=True)),
                ('creditos_acumulados', models.IntegerField(blank=True, null=True)),
                ('creditos_faltantes', models.IntegerField(blank=True, null=True)),
                ('promedio', models.FloatField(blank=True, null=True)),
                ('ciclos_cursados', models.IntegerField(blank=True, null=True)),
                ('maximo_ciclo', models.CharField(blank=True, max_length=10, null=True)),
                ('dictamen', models.CharField(blank=True, max_length=10, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('correo_personal', models.CharField(blank=True, max_length=150, null=True)),
                ('correo_institucional', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('retribucion_social', models.CharField(blank=True, max_length=150, null=True)),
                ('cvu', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_grado', models.DateField(blank=True, null=True)),
                ('tesis_titulo', models.CharField(blank=True, max_length=400, null=True)),
                ('protocolo', models.CharField(blank=True, max_length=1000, null=True)),
                ('impacto_cientifico', models.CharField(blank=True, max_length=1000, null=True)),
                ('impacto_social', models.CharField(blank=True, max_length=1000, null=True)),
                ('solucion_problemas', models.CharField(blank=True, max_length=1000, null=True)),
                ('estrategias_acceso', models.CharField(blank=True, max_length=1000, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=1000, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('lies', models.ForeignKey(blank=True, db_column='lies_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lies')),
                ('status', models.ForeignKey(blank=True, db_column='status_codigo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='core.statusalumno')),
            ],
            options={
                'db_table': 'alumno',
                'ordering': ['nombre'],
            },
        ),
    ]
