# Generated by Django 6.1.1 on 2026-09-15 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('tratamiento', models.CharField(blank=True, max_length=10, null=True)),
                ('grado', models.CharField(blank=True, max_length=150, null=True)),
                ('centro_universitario', models.CharField(blank=True, default='Centro Universitario de la Costa', max_length=150, null=True)),
                ('cvu', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('nucleo_academico', models.BooleanField(default=False)),
                ('sni', models.CharField(blank=True, max_length=10, null=True)),
                ('dedicacion', models.CharField(blank=True, max_length=60, null=True)),
                ('linea_investigacion', models.CharField(blank=True, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('lies', models.ForeignKey(blank=True, db_column='lies_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lies')),
            ],
            options={
                'db_table': 'profesor',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProfesorAlias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=150)),
                ('profesor', models.ForeignKey(db_column='profesor_id', on_delete=django.db.models.deletion.CASCADE, related_name='alias', to='profesores.profesor')),
            ],
            options={
                'db_table': 'profesor_alias',
            },
        ),
    ]
